-- Remaining products from the HPCM Price List effective 2026-10-01.
-- Generated from 'HPCM Pricing Guide.xlsx'. Items marked 'Pricing Varies' have no
-- list price; the order form asks for a price on those lines.
SET search_path = hpcm, public;
BEGIN;
INSERT INTO products (sku, name, category, pricing_unit, standard_length_in, price_varies, qbo_item_name) VALUES
    ('TRM-2X2X120', '2x2x120', 'trim', 'each', 120, false, '2x2x120'),
    ('TRM-2X4X120', '2x4x120', 'trim', 'each', 120, false, '2x4x120'),
    ('TRM-COUNTER-FLASHING', 'Counter Flashing', 'trim', 'each', 120, false, 'Counter Flashing'),
    ('TRM-D-STYLE-90', 'D style 90', 'trim', 'each', 120, false, 'D style 90'),
    ('TRM-DIVIDER-METAL', 'Divider Metal', 'trim', 'each', 120, false, 'Divider Metal'),
    ('TRM-DOUBLE-CLEAT', 'Double Cleat', 'trim', 'each', 120, true, 'Double Cleat'),
    ('TRM-DOWNSPOUT-BOX', 'Downspout (box)', 'trim', 'each', 120, true, 'Downspout (box)'),
    ('TRM-F-AND-J', 'F and J', 'trim', 'each', 120, false, 'F and J'),
    ('TRM-FACIA', 'Facia', 'trim', 'each', 120, true, 'Facia'),
    ('FLAT-FLAT-SHEET', 'Flat Sheet', 'flat_sheet', 'each', NULL, true, 'Flat Sheet'),
    ('TRM-GABLE-2X6', 'Gable 2x6', 'trim', 'each', 120, false, 'Gable 2x6'),
    ('TRM-GARAGE-DOOR-WRAP', 'Garage Door Wrap', 'trim', 'each', 120, true, 'Garage Door Wrap'),
    ('TRM-GUTTER', 'Gutter', 'trim', 'each', 120, true, 'Gutter'),
    ('TRM-HIGH-PROFILE-GABLE-S-S', 'High Profile Gable s/s', 'trim', 'each', 120, false, 'High Profile Gable s/s'),
    ('TRM-INVERTED-SOFFIT', 'Inverted Soffit', 'trim', 'each', 120, true, 'Inverted Soffit'),
    ('TRM-LOCKING-FACIA', 'Locking Facia', 'trim', 'each', 120, false, 'Locking Facia'),
    ('TRM-LOCKING-FACIA-CLEAT', 'Locking Facia Cleat', 'trim', 'each', 120, false, 'Locking Facia Cleat'),
    ('TRM-LOCKING-HEADWALL', 'Locking Headwall', 'trim', 'each', 120, false, 'Locking Headwall'),
    ('TRM-LOCKING-VALLEY', 'Locking Valley', 'trim', 'each', 120, false, 'Locking Valley'),
    ('TRM-LOW-PROFILE-CHANNEL-GABL', 'Low Profile Channel Gable', 'trim', 'each', 120, false, 'Low Profile Channel Gable'),
    ('TRM-OVERHEAD-DOOR-TRIM', 'Overhead Door Trim', 'trim', 'each', 120, true, 'Overhead Door Trim'),
    ('TRM-PARAPET-CAP', 'Parapet Cap', 'trim', 'each', 120, true, 'Parapet Cap'),
    ('TRM-PBR-J-CHANNEL', 'PBR J-Channel', 'trim', 'each', 120, false, 'PBR J-Channel'),
    ('TRM-PITCH-BREAK-TRANSITION', 'Pitch Break/Transition', 'trim', 'each', 120, false, 'Pitch Break/Transition'),
    ('TRM-RAT-GUARD', 'Rat Guard', 'trim', 'each', 120, false, 'Rat Guard'),
    ('TRM-SCUPPER', 'Scupper', 'trim', 'each', 120, true, 'Scupper'),
    ('TRM-SNOW-BAR', 'Snow Bar', 'trim', 'each', 120, false, 'Snow Bar'),
    ('TRM-SOFFIT', 'Soffit', 'trim', 'each', 120, true, 'Soffit'),
    ('TRM-SQUARE-BASE', 'Square Base', 'trim', 'each', 120, false, 'Square Base'),
    ('TRM-STANDING-SEAM-RIDGE-CAP', 'Standing Seam Ridge Cap', 'trim', 'each', 120, false, 'Standing Seam Ridge Cap'),
    ('TRM-STARTER-STRIP', 'Starter Strip', 'trim', 'each', 120, false, 'Starter Strip'),
    ('TRM-TOP-CAP-L-FLASH-S-S', 'Top Cap L Flash S/S', 'trim', 'each', 120, true, 'Top Cap L Flash S/S'),
    ('TRM-TRANSITION-METAL', 'Transition Metal', 'trim', 'each', 120, true, 'Transition Metal'),
    ('TRM-VALLEY-CAP', 'Valley Cap', 'trim', 'each', 120, false, 'Valley Cap'),
    ('TRM-VALLEY-CLEAT', 'Valley Cleat', 'trim', 'each', 120, false, 'Valley Cleat'),
    ('TRM-WIND-CLEAT', 'Wind Cleat', 'trim', 'each', 120, true, 'Wind Cleat'),
    ('TRM-WIND-CLIP', 'Wind Clip', 'trim', 'each', 120, true, 'Wind Clip'),
    ('TRM-Z-BAR-FOR-WAINSCOTING', 'Z Bar for Wainscoting', 'trim', 'each', 120, false, 'Z Bar for Wainscoting'),
    ('TRM-Z-TRACK', 'Z Track', 'trim', 'each', 120, true, 'Z Track'),
    ('TRM-Z-BAR-1IN', 'Z-Bar 1"', 'trim', 'each', 120, false, 'Z-Bar 1"'),
    ('TRM-Z-BAR-1-5IN', 'Z-Bar 1.5"', 'trim', 'each', 120, false, 'Z-Bar 1.5"'),
    ('BOOT-2-SPLIT-BOOT', '#2 Split Boot', 'boot', 'each', NULL, false, '#2 Split Boot'),
    ('BOOT-3-HI-TEMP-PIPE-BOOT', '#3 Hi-Temp Pipe Boot', 'boot', 'each', NULL, false, '#3 Hi-Temp Pipe Boot'),
    ('BOOT-5-HI-TEMP-PIPE-BOOT', '#5 Hi-Temp Pipe Boot', 'boot', 'each', NULL, false, '#5 Hi-Temp Pipe Boot'),
    ('BOOT-7-HI-TEMP-PIPE-BOOT', '#7 Hi-Temp Pipe Boot', 'boot', 'each', NULL, false, '#7 Hi-Temp Pipe Boot'),
    ('BOOT-7-PIPE-BOOT', '#7 Pipe Boot', 'boot', 'each', NULL, false, '#7 Pipe Boot'),
    ('JACK-2-PIPE-JACK', '#2 Pipe Jack', 'jack', 'each', NULL, false, '#2 Pipe Jack'),
    ('JACK-4-PIPE-JACK', '#4 Pipe Jack', 'jack', 'each', NULL, false, '#4 Pipe Jack'),
    ('JACK-5-PIPE-JACK', '#5 Pipe Jack', 'jack', 'each', NULL, false, '#5 Pipe Jack'),
    ('JACK-8-PIPE-JACK', '#8 Pipe Jack', 'jack', 'each', NULL, false, '#8 Pipe Jack'),
    ('SCR-2-1-2IN-WOODTITE-SCREW-1', '2 1/2" Woodtite Screw #10', 'fastener', 'bag', NULL, false, '2 1/2" Woodtite Screw #10'),
    ('SCR-2IN-SCREWS-OVERSIZE', '2" Screws Oversize', 'fastener', 'bag', NULL, false, '2" Screws Oversize'),
    ('SCR-OVERSIZE-14-SCREWS', 'Oversize #14 screws', 'fastener', 'bag', NULL, false, 'Oversize #14 screws'),
    ('SCR-10-1-5-WOODTITE-SCREWS', '#10 1.5 Woodtite Screws', 'fastener', 'bag', NULL, false, '#10 1.5 Woodtite Screws'),
    ('SCR-STITCH-SCREWS', 'Stitch Screws', 'fastener', 'bag', NULL, false, 'Stitch Screws'),
    ('ACC-EM-SEAL', 'Em Seal', 'accessory', 'each', NULL, false, 'Em Seal'),
    ('ACC-PBR-CLOSURE', 'PBR Closure', 'accessory', 'each', NULL, false, 'PBR Closure'),
    ('ACC-RIVETS', 'Rivets', 'accessory', 'bag', NULL, false, 'Rivets'),
    ('ACC-S5-SNOWBAR', 'S5 Snowbar', 'accessory', 'each', NULL, false, 'S5 Snowbar'),
    ('ACC-S5U-SNOWBAR-CLAMPS', 'S5U Snowbar Clamps', 'accessory', 'each', NULL, false, 'S5U Snowbar Clamps'),
    ('ACC-S5U-VERSA-CLIPS', 'S5U Versa Clips', 'accessory', 'each', NULL, false, 'S5U Versa Clips'),
    ('ACC-SNAP-Z-VENT', 'Snap Z Vent', 'accessory', 'each', NULL, false, 'Snap Z Vent'),
    ('ACC-UNIVERSAL-CLOSURE', 'Universal Closure', 'accessory', 'each', NULL, false, 'Universal Closure'),
    ('ACC-VENTED-CLOSURE-THROUGH-F', 'Vented Closure (through fastener)', 'accessory', 'each', NULL, false, 'Vented Closure (through fastener)'),
    ('ACC-VERSA-VENT', 'Versa Vent', 'accessory', 'each', NULL, false, 'Versa Vent')
ON CONFLICT (sku) DO NOTHING;

INSERT INTO product_prices (product_id, unit_price, effective_from, source)
SELECT p.product_id, v.price, DATE '2026-10-01', 'HPCM Price List 2026-10-01'
FROM (VALUES
    ('TRM-2X2X120', 15.3),
    ('TRM-2X4X120', 20.4),
    ('TRM-COUNTER-FLASHING', 18.25),
    ('TRM-D-STYLE-90', 20.4),
    ('TRM-DIVIDER-METAL', 34.0),
    ('TRM-F-AND-J', 34.85),
    ('TRM-GABLE-2X6', 45.05),
    ('TRM-HIGH-PROFILE-GABLE-S-S', 42.87),
    ('TRM-LOCKING-FACIA', 30.46),
    ('TRM-LOCKING-FACIA-CLEAT', 19.55),
    ('TRM-LOCKING-HEADWALL', 52.7),
    ('TRM-LOCKING-VALLEY', 74.8),
    ('TRM-LOW-PROFILE-CHANNEL-GABL', 34.0),
    ('TRM-PBR-J-CHANNEL', 18.28),
    ('TRM-PITCH-BREAK-TRANSITION', 49.3),
    ('TRM-RAT-GUARD', 19.42),
    ('TRM-SNOW-BAR', 27.2),
    ('TRM-SQUARE-BASE', 46.75),
    ('TRM-STANDING-SEAM-RIDGE-CAP', 44.2),
    ('TRM-STARTER-STRIP', 13.0),
    ('TRM-VALLEY-CAP', 51.0),
    ('TRM-VALLEY-CLEAT', 14.0),
    ('TRM-Z-BAR-FOR-WAINSCOTING', 18.0),
    ('TRM-Z-BAR-1IN', 15.0),
    ('TRM-Z-BAR-1-5IN', 16.5),
    ('BOOT-2-SPLIT-BOOT', 46.32),
    ('BOOT-3-HI-TEMP-PIPE-BOOT', 31.8),
    ('BOOT-5-HI-TEMP-PIPE-BOOT', 71.8),
    ('BOOT-7-HI-TEMP-PIPE-BOOT', 120.0),
    ('BOOT-7-PIPE-BOOT', 45.0),
    ('JACK-2-PIPE-JACK', 25.0),
    ('JACK-4-PIPE-JACK', 35.0),
    ('JACK-5-PIPE-JACK', 38.0),
    ('JACK-8-PIPE-JACK', 55.0),
    ('SCR-2-1-2IN-WOODTITE-SCREW-1', 40.0),
    ('SCR-2IN-SCREWS-OVERSIZE', 80.0),
    ('SCR-OVERSIZE-14-SCREWS', 80.0),
    ('SCR-10-1-5-WOODTITE-SCREWS', 30.0),
    ('SCR-STITCH-SCREWS', 38.0),
    ('ACC-EM-SEAL', 28.0),
    ('ACC-PBR-CLOSURE', 1.4),
    ('ACC-RIVETS', 38.0),
    ('ACC-S5-SNOWBAR', 50.05),
    ('ACC-S5U-SNOWBAR-CLAMPS', 15.0),
    ('ACC-S5U-VERSA-CLIPS', 3.0),
    ('ACC-SNAP-Z-VENT', 6.1),
    ('ACC-UNIVERSAL-CLOSURE', 2.3),
    ('ACC-VENTED-CLOSURE-THROUGH-F', 2.5),
    ('ACC-VERSA-VENT', 4.0)
) AS v(sku, price)
JOIN products p ON p.sku = v.sku
ON CONFLICT (product_id, effective_from) DO NOTHING;
COMMIT;
